import { expect, test } from '@playwright/test'

test('dashboard navigation, details and launcher controls work', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Dashboard' })).toBeVisible()
  await expect(page.getByText('Demo data')).toBeVisible()
  await expect(page.getByText('No MCP clients')).toBeVisible()
  await expect(page.getByText('MCP Connected')).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Favorites & Quick launch' })).toBeVisible()
  await expect(page.getByTestId('quick-command-cmd-global-db')).toBeVisible()
  await expect(page.getByTestId('quick-stack-stack-internal')).toBeVisible()
  await page.getByTestId('quick-command-cmd-global-db').getByRole('button', { name: 'View Local PostgreSQL details' }).click()
  await expect(page.getByTestId('command-detail-drawer')).toBeVisible()
  await expect(page.getByTestId('command-detail-drawer')).toContainText('not verified')
  await expect(page.getByTestId('command-detail-drawer')).toContainText('Pre-existing ports are never attributed')
  await page.getByTestId('command-detail-drawer').getByRole('button', { name: 'Close launcher details' }).click()

  await page.getByTestId('quick-command-cmd-api').getByRole('button', { name: 'View Backend API details' }).click()
	await expect(page.getByTestId('command-tab-checks & tests')).toBeVisible()
	await page.getByTestId('command-tab-checks & tests').click()
	await expect(page.getByTestId('check-card-check-smoke')).toContainText('Backend smoke test')
  await page.getByTestId('command-tab-logs').click()
  await expect(page.getByTestId('command-log-panel')).toContainText('server listening')
  await expect(page.getByTestId('command-log-panel').locator('.log-line-warn')).toContainText('slow query')
  await expect(page.getByTestId('command-detail-drawer').getByText('Live', { exact: true })).toBeVisible()
  await page.getByTestId('copy-logs-command-log-panel').click()
  await expect(page.getByTestId('copy-logs-command-log-panel')).toHaveAttribute('aria-label', 'Copied')
  await page.getByTestId('command-detail-drawer').getByRole('button', { name: 'Close launcher details' }).click()

  await page.getByTestId('quick-stack-stack-internal').getByRole('button', { name: 'View Internal Microservices details' }).click()
	await expect(page.getByTestId('stack-tab-checks & tests')).toBeVisible()
	await page.getByTestId('stack-tab-checks & tests').click()
	await expect(page.getByTestId('check-card-check-health')).toContainText('http://127.0.0.1:8080/health')
	await expect(page.getByTestId('check-card-check-health')).toContainText('Local')
	await expect(page.getByTestId('check-card-check-staging-health')).toContainText('Remote')
	await expect(page.getByTestId('check-card-check-staging-health')).toContainText('https://staging.example.com/health')
  await page.getByTestId('stack-tab-logs').click()
  await expect(page.getByTestId('stack-log-member-cmd-api')).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByTestId('stack-log-panel')).toContainText('starting make go')
  await page.getByTestId('stack-detail-drawer').getByRole('button', { name: 'Close stack details' }).click()

  await page.getByTestId('quick-start-command-cmd-global-db').click()
  await expect(page.getByTestId('quick-stop-command-cmd-global-db')).toBeVisible()
  await expect(page.getByTestId('quick-command-cmd-global-db')).toContainText('started unverified')
  await expect(page.getByTestId('run-card-run-api')).toBeVisible()
  const historyPanel = page.locator('section.panel').filter({ has: page.getByRole('heading', { name: 'Command History' }) })
  const portsPanel = page.locator('section.panel').filter({ has: page.getByRole('heading', { name: 'Port Overview' }) })
  const historyBox = await historyPanel.boundingBox()
  const portsBox = await portsPanel.boundingBox()
  expect(Math.abs((historyBox?.width ?? 0) - (portsBox?.width ?? 0))).toBeLessThan(2)
  expect(portsBox?.y ?? 0).toBeGreaterThan((historyBox?.y ?? 0) + (historyBox?.height ?? 0) - 1)
  await expect.poll(() => historyPanel.locator('.command-link strong').first().evaluate(element => getComputedStyle(element).textOverflow)).toBe('ellipsis')

  await page.getByTestId('history-promote-hist-test').click()
  await expect(page.getByTestId('promote-modal')).toBeVisible()
  await expect(page.getByTestId('promote-modal')).toContainText('go test ./...')
  await page.getByTestId('promote-modal').getByRole('button', { name: 'New project' }).click()
  await page.getByLabel('New project name').fill('Dashboard project')
  await page.getByTestId('create-project-inline').click()
  await expect(page.getByLabel('Project')).toHaveValue(/project-/)
  await page.getByTestId('promote-modal').getByRole('button', { name: 'New collection' }).click()
  await page.getByLabel('New collection name').fill('Dashboard launchers')
  await page.getByTestId('create-collection-inline').click()
  await expect(page.getByLabel('Collection')).toHaveValue(/collection-/)
  await page.getByTestId('promote-modal').getByRole('button', { name: 'Cancel' }).click()

  await page.getByTestId('run-card-run-api').getByRole('button', { name: 'View logs for Backend API' }).click()
  await expect(page.getByTestId('detail-tab-logs')).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByTestId('log-panel')).toContainText('server listening')
  await page.getByTestId('run-detail-drawer').getByRole('button', { name: 'Close run details' }).click()

  await page.getByTestId('run-card-run-api').getByRole('button', { name: 'Inspect Backend API' }).click()
  await expect(page.getByTestId('run-detail-drawer')).toBeVisible()
	await expect(page.getByTestId('detail-tab-checks & tests')).toBeVisible()
  await page.getByTestId('detail-tab-logs').click()
  await expect(page.getByTestId('log-panel')).toContainText('server listening')
  await page.getByTestId('run-detail-drawer').getByRole('button', { name: 'Close run details' }).click()

  await page.getByRole('navigation', { name: 'Main navigation' }).getByRole('button', { name: 'Logs', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Live Logs' })).toBeVisible()
  await expect(page.getByTestId('logs-page').getByRole('tab', { name: 'Butcembu API', exact: true })).toBeVisible()
  await expect(page.getByTestId('logs-page').getByRole('tab', { name: /:8080/ })).toBeVisible()
  await expect(page.getByTestId('live-log-terminal')).toContainText('starting make go')
  await page.getByTestId('logs-page').getByRole('tab', { name: 'Butcembu Web', exact: true }).click()
  await expect(page.getByTestId('logs-page').getByRole('tab', { name: /:3000/ })).toBeVisible()
  await expect(page.getByTestId('live-log-terminal')).toContainText('starting npm run dev')
  await page.getByTestId('copy-logs-live-log-terminal').click()
  await expect(page.getByTestId('copy-logs-live-log-terminal')).toHaveAttribute('aria-label', 'Copied')
  await page.getByTestId('copy-live-command').click()
  await expect(page.getByTestId('copy-live-command')).toHaveAttribute('aria-label', 'Copied')

  await page.getByRole('button', { name: 'Services' }).click()
  await expect(page.getByRole('heading', { name: 'Saved Services' })).toBeVisible()
  const workerCommand = page.getByTestId('command-card-cmd-worker').locator('.catalog-command code')
  await expect.poll(() => workerCommand.evaluate(element => getComputedStyle(element).webkitLineClamp)).toBe('3')
  await expect.poll(() => workerCommand.evaluate(element => getComputedStyle(element).overflow)).toBe('hidden')
  await page.getByTestId('copy-command-cmd-worker').click()
  await expect(page.getByTestId('copy-command-cmd-worker')).toHaveAttribute('aria-label', 'Copied')
  await expect(page.getByTestId('command-detail-drawer')).toHaveCount(0)
  await page.getByTestId('command-card-cmd-worker').click()
  await expect(page.getByTestId('command-detail-drawer')).toContainText('./scripts/worker.sh')
  await expect(page.getByTestId('copy-command')).toBeVisible()
	await expect(page.getByTestId('command-tab-checks & tests')).toHaveCount(0)
  await page.getByTestId('command-tab-script').click()
  await expect(page.getByTestId('command-script-panel')).toContainText('set -euo pipefail')
  await page.getByTestId('copy-script').click()
  await expect(page.getByTestId('copy-script')).toHaveAttribute('aria-label', 'Copied')
  await page.getByTestId('command-detail-drawer').getByRole('button', { name: 'Close launcher details' }).click()
  await page.getByTestId('command-card-cmd-api').click()
  await expect(page.getByTestId('copy-command')).toBeVisible()
  await expect(page.getByTestId('copy-command-output-preview')).toBeVisible()
  await page.getByTestId('command-tab-runs').click()
  await expect(page.getByTestId('command-detail-drawer')).toContainText('make go')
  await page.getByTestId('command-detail-drawer').getByRole('button', { name: 'make go' }).click()
  await expect(page.getByTestId('command-log-panel')).toContainText('server listening')
  await page.getByTestId('command-detail-drawer').getByRole('button', { name: 'Close launcher details' }).click()
  await page.getByTestId('start-command-cmd-worker').click()
  await expect(page.getByTestId('stop-command-cmd-worker')).toBeVisible()
  await page.getByRole('button', { name: 'Add Notification Worker to favorites' }).click()
  await expect(page.getByRole('button', { name: 'Remove Notification Worker from favorites' })).toBeVisible()
	await page.getByTestId('stop-command-cmd-worker').click()

	await page.getByRole('button', { name: 'Tasks' }).click()
	await page.getByTestId('command-card-cmd-build').click()
	await page.getByTestId('command-tab-logs').click()
	await expect(page.getByTestId('command-log-panel').locator('.log-line-error')).toContainText('ERROR build failed')
	await page.getByTestId('command-detail-drawer').getByTestId('log-filter-errors').click()
	await expect(page.getByTestId('command-log-panel')).toContainText('ERROR build failed')
	await expect(page.getByTestId('command-log-panel')).not.toContainText('connected to database')
	await page.getByTestId('delete-command-cmd-build').click()
	await expect(page.getByTestId('delete-saved-dialog')).toContainText('Previous Runs, logs, and History entries are retained')
	await page.getByTestId('confirm-delete-saved').click()
	await expect(page.getByTestId('command-card-cmd-build')).toHaveCount(0)

  await page.getByRole('button', { name: 'Stacks' }).click()
  await expect(page.getByTestId('stack-card-stack-internal')).toBeVisible()
  await expect(page.getByTestId('stack-card-stack-internal').getByTestId('stack-env-badge')).toHaveText('local')
	await page.getByTestId('stack-card-stack-internal').click()
	await expect(page.getByTestId('stack-environment-stack-internal')).toHaveValue('local')
	const stackDrawer = page.getByTestId('stack-detail-drawer')
	await expect(stackDrawer).toContainText('Choose members to start')
	await expect(page.getByTestId('stack-member-cmd-api').getByRole('checkbox')).toBeDisabled()
	await page.getByTestId('stack-member-cmd-worker').getByRole('checkbox').check()
	await expect(page.getByTestId('start-selected-stack-stack-internal')).toContainText('Start selected (1)')
	await page.getByTestId('start-selected-stack-stack-internal').click()
	await expect(page.getByTestId('start-selected-stack-stack-internal')).toContainText('Start selected (0)')
	await expect(page.getByTestId('stack-member-log-cmd-worker')).toHaveCount(0)
	await page.getByTestId('stack-member-cmd-worker').click()
	await expect(page.getByTestId('stack-member-log-cmd-worker')).toBeVisible()
	await page.getByTestId('stack-member-cmd-worker').click()
	await expect(page.getByTestId('stack-member-log-cmd-worker')).toHaveCount(0)
	await stackDrawer.getByRole('button', { name: 'Close stack details' }).click()
  await page.getByTestId('restart-stack-stack-internal').click()
  await expect(page.getByTestId('stop-stack-stack-internal')).toBeVisible()
	await page.getByTestId('stop-stack-stack-internal').click()
	await expect(page.getByTestId('start-stack-stack-internal')).toContainText('Start all')
	await page.getByTestId('delete-stack-stack-internal').click()
	await expect(page.getByTestId('delete-saved-dialog')).toContainText('launchers inside this stack are kept')
	await page.getByTestId('confirm-delete-saved').click()
	await expect(page.getByTestId('stack-card-stack-internal')).toHaveCount(0)

  await page.getByRole('button', { name: 'Ports' }).click()
  await expect(page.getByRole('button', { name: 'Copy address for port 5432' })).toBeVisible()

  await page.getByTestId('workspace-picker-toggle').click()
  await expect(page.getByTestId('workspace-option-all')).toBeVisible()
  await page.getByTestId('workspace-option-project-api').click()
  await expect(page).toHaveURL(/\/w\/butcembu-api(\/ports)?$/)
  await expect(page.getByText('Butcembu API workspace')).toBeVisible()
  await page.getByRole('navigation', { name: 'Main navigation' }).getByRole('button', { name: 'Services', exact: true }).click()
  await expect(page).toHaveURL(/\/w\/butcembu-api\/services$/)
  await expect(page.getByTestId('command-card-cmd-api')).toBeVisible()
  await expect(page.getByTestId('command-card-cmd-web')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Core services', exact: true })).toBeVisible()
  await expect(page.getByText('Added by Claude Code · discovered from Makefile').first()).toBeVisible()
  await page.getByTestId('add-collection').click()
  await page.getByRole('dialog', { name: 'New collection' }).getByLabel('Name').fill('Release ops')
  await page.getByTestId('confirm-collection').click()
  await expect(page.getByRole('button', { name: 'Release ops', exact: true })).toBeVisible()

  await page.getByRole('button', { name: 'History' }).click()
  await page.getByTestId('history-promote-run-api').click()
  await expect(page.getByTestId('promote-modal')).toBeVisible()
  await page.getByLabel('Project').selectOption('project-web')
  await page.getByLabel('Collection').selectOption('collection-web-dev')
  await page.getByLabel('Tags').fill('release, web')
  await page.getByLabel('Pin to favorites').check()
  await expect(page.getByTestId('promote-modal').getByText('Ports are not selected automatically')).toBeVisible()
  await expect(page.getByTestId('promote-modal').getByRole('checkbox').first()).not.toBeChecked()
  await page.getByTestId('confirm-promote').click()
  await expect(page.getByTestId('promotion-receipt')).toContainText('Launcher saved')
  await page.getByTestId('promotion-receipt').getByRole('button', { name: 'Open workspace' }).click()
  await expect(page).toHaveURL(/\/w\/butcembu-web\/services$/)
  await expect(page.getByText('Butcembu Web workspace')).toBeVisible()
  await expect(page.getByText('Saved from history').first()).toBeVisible()

  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Settings' })).toBeVisible()
  await expect(page.getByText('No MCP clients connected', { exact: true })).toBeVisible()
  await page.getByTestId('open-shutdown').click()
  await expect(page.getByRole('dialog', { name: 'Stop AgentShell?' })).toContainText('active runs')
  await expect(page.locator('.shutdown-impact').getByText('3', { exact: true })).toBeVisible()
  await page.getByTestId('confirm-shutdown').click()
  await expect(page.getByRole('heading', { name: 'Demo runtime stopped' })).toBeVisible()
})

test('page routes survive refresh and history shows source clients with output previews', async ({ page }) => {
	await page.goto('/history')
	await expect(page).toHaveURL(/\/history$/)
	await expect(page.getByRole('heading', { name: 'Command History' })).toBeVisible()
	await expect(page.getByText('Cursor', { exact: true })).toBeVisible()
	await expect(page.getByTestId('history-output-hist-test')).toContainText('ok github.com/agentshell/store')
	await page.getByTestId('history-command-hist-test').click()
	const runOutput = page.getByTestId('run-output-preview')
	await expect(runOutput).toContainText('server listening and ready')
	await runOutput.click()
	await expect(page.getByTestId('detail-tab-logs')).toHaveAttribute('aria-selected', 'true')
	await page.getByTestId('run-detail-drawer').getByRole('button', { name: 'Close run details' }).click()

	await page.getByTestId('history-output-hist-test').click()
	await expect(page.getByTestId('detail-tab-logs')).toHaveAttribute('aria-selected', 'true')
	await page.getByTestId('run-detail-drawer').getByRole('button', { name: 'Close run details' }).click()

	await page.getByRole('navigation', { name: 'Main navigation' }).getByRole('button', { name: 'Services', exact: true }).click()
	await expect(page).toHaveURL(/\/services$/)
	await expect(page.getByRole('heading', { name: 'Saved Services' })).toBeVisible()
	await page.reload()
	await expect(page).toHaveURL(/\/services$/)
	await expect(page.getByRole('heading', { name: 'Saved Services' })).toBeVisible()

	await page.goBack()
	await expect(page).toHaveURL(/\/history$/)
	await expect(page.getByRole('heading', { name: 'Command History' })).toBeVisible()
})

test('workspace picker scopes pages and survives refresh', async ({ page }) => {
  await page.goto('/')
  await page.getByTestId('workspace-picker-toggle').click()
  await page.getByTestId('workspace-option-project-api').click()
  await expect(page).toHaveURL(/\/w\/butcembu-api$/)
  await expect(page.getByTestId('workspace-stack-stack-internal')).toBeVisible()
  await page.getByRole('navigation', { name: 'Main navigation' }).getByRole('button', { name: 'Services', exact: true }).click()
  await expect(page.getByTestId('command-card-cmd-api')).toBeVisible()
  await expect(page.getByTestId('command-card-cmd-web')).toHaveCount(0)
  await page.reload()
  await expect(page).toHaveURL(/\/w\/butcembu-api\/services$/)
  await expect(page.getByText('Butcembu API workspace')).toBeVisible()
  await page.getByRole('navigation', { name: 'Main navigation' }).getByRole('button', { name: 'Logs', exact: true }).click()
  await expect(page).toHaveURL(/\/w\/butcembu-api\/logs$/)
  await expect(page.getByTestId('logs-page').getByRole('tab', { name: 'Butcembu API', exact: true })).toHaveCount(0)
  await expect(page.getByTestId('logs-page').getByRole('tab', { name: /:8080/ })).toBeVisible()
  await page.getByTestId('workspace-picker-toggle').click()
  await page.getByTestId('workspace-option-all').click()
  await expect(page).toHaveURL(/\/logs$/)
})

test('external stack members show observed state and open launcher details', async ({ page }) => {
	await page.goto('/')
	await page.getByRole('button', { name: 'Stacks' }).click()
	await page.getByTestId('stack-card-stack-external').click()
	const member = page.getByTestId('stack-member-cmd-external-infra')
	await expect(member).toContainText(/running/i)
	await expect(member).toContainText('External')
	await expect(member).toContainText('Expected MySQL port is listening')
	await expect(page.getByTestId('stack-member-stop-cmd-external-infra')).toBeVisible()
	await page.getByTestId('stack-member-details-cmd-external-infra').click()
	await expect(page.getByTestId('stack-detail-drawer')).toHaveCount(0)
	const drawer = page.getByTestId('command-detail-drawer')
	await expect(page.getByTestId('drawer-back')).toContainText('Back to External infrastructure')
	await expect(drawer).toContainText('Detached infrastructure')
	await expect(drawer).toContainText('Observed state')
	await expect(drawer).toContainText('running')
	await expect(drawer).toContainText('docker compose up -d mysql redis')
	await expect(drawer).toContainText('docker compose stop mysql redis')
	const preview = page.getByTestId('command-output-preview')
	await expect(preview).toContainText('server listening and ready')
	await page.getByTestId('command-tab-runs').click()
	await expect(drawer).toContainText('start · docker compose up -d mysql redis')
	await page.getByTestId('command-tab-overview').click()
	await preview.click()
	await expect(page.getByTestId('command-tab-logs')).toHaveAttribute('aria-selected', 'true')
	await expect(page.getByTestId('command-log-panel')).toContainText('docker compose up -d mysql redis')
	await page.getByTestId('drawer-back').click()
	await expect(page.getByTestId('command-detail-drawer')).toHaveCount(0)
	await expect(page.getByTestId('stack-detail-drawer')).toContainText('External infrastructure')
})

test('checks are inspected before execution and can be collapsed, copied, edited and deleted', async ({ page }) => {
	await page.goto('/')
	await page.getByTestId('quick-stack-stack-internal').getByRole('button', { name: 'View Internal Microservices details' }).click()
	await page.getByTestId('stack-tab-checks & tests').click()

	await page.getByTestId('select-check-check-health').click()
	await expect(page.getByTestId('check-request-tab')).toHaveAttribute('aria-selected', 'true')
	await expect(page.getByTestId('check-detail-panel')).toContainText('Inspecting this definition does not send a request')
	await expect(page.getByTestId('check-detail-panel')).toContainText('GET http://127.0.0.1:8080/health')
	await page.getByTestId('check-response-tab').click()
	await expect(page.getByTestId('check-detail-panel')).toContainText('No Runs yet')

	await page.getByTestId('check-request-tab').click()
	await page.getByTestId('run-selected-check-check-health').click()
	await expect(page.getByTestId('check-response-tab')).toHaveAttribute('aria-selected', 'true')
	await expect(page.getByTestId('check-log-panel')).toContainText('HTTP GET http://127.0.0.1:8080/health')

	await page.getByTestId('toggle-all-checks').click()
	await expect(page.locator('.check-card-body')).toHaveCount(0)
	await page.getByTestId('toggle-all-checks').click()
	await expect(page.locator('.check-card-body')).toHaveCount(2)
	await page.getByTestId('toggle-check-check-health').click()
	await expect(page.getByTestId('check-card-check-health').locator('.check-card-body')).toHaveCount(0)
	await page.getByTestId('toggle-check-check-health').click()

	await page.getByTestId('check-card-check-staging-health').locator('code').click()
	await expect(page.getByTestId('check-detail-panel')).toContainText('https://staging.example.com/health')
	await page.getByTestId('check-edit-tab').click()
	let editor = page.getByTestId('check-editor')
	await editor.getByLabel('Name').fill('Temporary staging health')
	await editor.getByLabel('URL').fill('https://copy.example.com/health')
	await page.getByTestId('run-check-draft').click()
	await expect(page.getByTestId('check-response-tab')).toHaveAttribute('aria-selected', 'true')
	await expect(page.getByTestId('check-log-panel')).toContainText('https://copy.example.com/health')
	await page.getByTestId('check-request-tab').click()
	await expect(page.getByTestId('check-detail-panel')).toContainText('https://staging.example.com/health')
	await expect(page.getByTestId('check-detail-panel')).not.toContainText('Temporary staging health')

	await page.getByTestId('check-edit-tab').click()
	editor = page.getByTestId('check-editor')
	await expect(editor.getByLabel('Name')).toHaveValue('Temporary staging health')
	await expect(editor.getByLabel('URL')).toHaveValue('https://copy.example.com/health')
	await editor.getByLabel('Name').fill('Staging health copy')
	await editor.getByLabel('Body contains').fill('healthy')
	await page.getByTestId('save-check-copy').click()
	const copy = page.locator('[data-testid^="check-card-"]').filter({ hasText: 'Staging health copy' })
	await expect(copy).toBeVisible()
	await expect(page.getByTestId('check-card-check-staging-health')).toContainText('Staging health')
	await expect(page.getByTestId('check-detail-panel')).toContainText('healthy')

	await page.getByTestId('check-edit-tab').click()
	await page.getByTestId('delete-check').click()
	await expect(page.getByTestId('check-editor')).toContainText('Previous Runs and logs will remain')
	await page.getByTestId('confirm-delete-check').click()
	await expect(copy).toHaveCount(0)
})

test('light and dark theme selection persists', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await expect(page.locator('meta[name="theme-color"]')).toHaveAttribute('content', '#f6f8fb')

  await page.getByTestId('theme-toggle').click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.locator('meta[name="theme-color"]')).toHaveAttribute('content', '#090a09')
  expect(await page.evaluate(() => {
    const styles = getComputedStyle(document.documentElement)
    return Object.fromEntries(['--bg', '--surface', '--green', '--purple', '--orange', '--red'].map(token => [
      token,
      styles.getPropertyValue(token).trim(),
    ]))
  })).toEqual({
    '--bg': '#090a09',
    '--surface': '#111211',
    '--green': '#55d85a',
    '--purple': '#b56be3',
    '--orange': '#ff9800',
    '--red': '#ff453a',
  })
  expect(await page.evaluate(() => localStorage.getItem('agentshell.theme'))).toBe('dark')

  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.getByTestId('theme-toggle').click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  expect(await page.evaluate(() => localStorage.getItem('agentshell.theme'))).toBe('light')
})

test('stack orchestration can be configured from the dashboard', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Stacks' }).click()
  await page.getByTestId('stop-stack-stack-internal').click()
  await expect(page.getByTestId('start-stack-stack-internal')).toContainText('Start all')
  await page.getByTestId('stack-card-stack-internal').click()
  const drawer = page.getByTestId('stack-detail-drawer')
  await expect(drawer.getByText(/after Backend API/)).toBeVisible()
  await expect(page.getByTestId('stack-prereq-summary-stack-external')).toContainText('External infrastructure')
  await expect(page.getByTestId('stack-prereq-summary-stack-external')).toContainText('90s')
  await page.getByTestId('edit-stack-orchestration-stack-internal').click()
  await expect(page.getByTestId('stack-orchestration-editor')).toBeVisible()
  await expect(page.getByTestId('stack-prereq-stack-external')).toBeChecked()

  await page.getByLabel('Stack start strategy').selectOption('sequential')
  const worker = page.getByTestId('stack-member-config-cmd-worker')
  await expect(worker.getByLabel('Backend API', { exact: true })).toBeChecked()
  await worker.getByLabel('Notification Worker wait condition').selectOption('ready')
  await worker.getByLabel('Notification Worker wait timeout').fill('45000')
  await page.getByTestId('save-stack-orchestration-stack-internal').click()

  await expect(page.getByTestId('stack-orchestration-editor')).toHaveCount(0)
  await expect(drawer).toContainText('sequential')
  await expect(drawer.getByText(/wait ready · 45000 ms/)).toBeVisible()
  await page.getByTestId('edit-stack-orchestration-stack-internal').click()
  await expect(page.getByLabel('Stack start strategy')).toHaveValue('sequential')
  await expect(page.getByLabel('Notification Worker wait condition')).toHaveValue('ready')
})

test('starting a stack asks before starting prerequisite stacks', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Stacks' }).click()
  await page.getByTestId('stop-stack-stack-external').click()
  await page.getByTestId('start-stack-stack-internal').click()
  const dialog = page.getByTestId('stack-prerequisites-dialog')
  await expect(dialog).toContainText('External infrastructure')
  await page.getByTestId('confirm-start-prerequisites').click()
  await expect(dialog).toHaveCount(0)
  await expect(page.getByTestId('stop-stack-stack-external')).toBeVisible()
})

test('a stack can be created in the UI and opens directly in orchestration', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Stacks' }).click()
  await page.getByTestId('new-stack').click()
  const dialog = page.getByTestId('stack-create-dialog')
  await dialog.getByLabel('Name').fill('Local application')
  await page.getByLabel('Stack project').selectOption('project-api')
  await dialog.getByText('Backend API').click()
  await dialog.getByText('Notification Worker').click()
  await page.getByTestId('confirm-stack-create').click()

  const editor = page.getByTestId('stack-orchestration-editor')
  await expect(editor).toBeVisible()
  const worker = editor.getByTestId(/stack-member-config-cmd-worker/)
  await worker.getByLabel('Backend API', { exact: true }).check()
  await page.getByRole('button', { name: 'Save orchestration' }).click()
  await expect(editor).toHaveCount(0)
  await expect(page.getByTestId('stack-detail-drawer')).toContainText('after Backend API')
})

test('parameterized launcher prompts for one-shot secret input', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('link[rel="icon"][type="image/svg+xml"]')).toHaveAttribute('href', '/agent_shell_logo.svg')
  expect((await page.request.get('/agent_shell_logo.svg')).status()).toBe(200)
  expect((await page.request.get('/agent_shell_logo.png')).status()).toBe(200)
  expect((await page.request.get('/agent_shell_logo-32.png')).status()).toBe(200)

  await page.getByRole('button', { name: 'Tasks', exact: true }).click()
  const card = page.getByTestId('command-card-cmd-vault-unseal')
  await card.getByTestId('start-command-cmd-vault-unseal').click()

  const dialog = page.getByTestId('parameter-dialog')
  await expect(dialog).toContainText('Run Vault unseal')
  const secret = dialog.getByLabel('Vault unseal key')
  await expect(secret).toHaveAttribute('type', 'password')
  await expect(secret).toHaveValue('')
  await secret.fill('one-shot-browser-secret')
  await dialog.getByTestId('submit-parameters').click()

  await expect(dialog).toHaveCount(0)
  await expect(card).toContainText('running')
  await expect(page.getByText('one-shot-browser-secret')).toHaveCount(0)

  await card.getByTestId('restart-command-cmd-vault-unseal').click()
  await expect(page.getByTestId('parameter-dialog').getByLabel('Vault unseal key')).toHaveValue('')
})

test('tests page lists, searches, runs and opens the owning stack or launcher', async ({ page }) => {
  await page.goto('/tests')
  await expect(page).toHaveURL(/\/tests$/)
  await expect(page.getByRole('heading', { name: 'Tests' })).toBeVisible()
  await expect(page.getByTestId('test-card-check-health')).toBeVisible()
  await expect(page.getByTestId('test-card-check-smoke')).toBeVisible()
  await expect(page.getByTestId('test-card-check-run-health')).toBeVisible()

  await page.getByTestId('tests-search').fill('staging')
  await expect(page.getByTestId('test-card-check-staging-health')).toBeVisible()
  await expect(page.getByTestId('test-card-check-health')).toHaveCount(0)

  await page.getByTestId('tests-search').fill('')
  await page.getByTestId('tests-tag-filter-smoke').click()
  await expect(page.getByTestId('test-card-check-health')).toBeVisible()
  await expect(page.getByTestId('test-card-check-staging-health')).toHaveCount(0)
  await page.getByTestId('tests-tag-filter-all').click()
  await page.getByTestId('tests-filter-kind-command').click()
  await expect(page.getByTestId('test-card-check-smoke')).toBeVisible()
  await expect(page.getByTestId('test-card-check-health')).toHaveCount(0)

  await page.getByTestId('tests-filter-kind-all').click()
  await page.getByTestId('test-card-check-health').click()
  const drawer = page.getByTestId('test-detail-drawer')
  await expect(drawer).toBeVisible()
  await expect(page.getByTestId('check-detail-panel')).toContainText('http://127.0.0.1:8080/health')
  await page.getByTestId('run-selected-check-check-health').click()
  await expect(page.getByTestId('check-response-tab')).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByTestId('open-test-owner')).toHaveText('Internal Microservices')
  await page.getByTestId('open-test-owner').click()
  await expect(page.getByTestId('test-detail-drawer')).toHaveCount(0)
  await expect(page.getByTestId('stack-detail-drawer')).toBeVisible()
  await expect(page.getByTestId('stack-detail-drawer')).toContainText('Internal Microservices')
  await expect(page.getByTestId('drawer-back')).toContainText('Back to API health')
  await page.getByTestId('drawer-back').click()
  await expect(page.getByTestId('test-detail-drawer')).toBeVisible()
  await page.getByTestId('open-test-owner').click()
  await page.getByTestId('stack-detail-drawer').getByRole('button', { name: 'Close stack details' }).click()

  await page.getByTestId('open-test-owner-check-smoke').click()
  await expect(page.getByTestId('command-detail-drawer')).toBeVisible()
  await expect(page.getByTestId('command-detail-drawer')).toContainText('Backend API')
})

test('launcher lists filter by tags', async ({ page }) => {
  await page.goto('/services')
  await expect(page.getByTestId('command-card-cmd-api')).toBeVisible()
  await expect(page.getByTestId('command-card-cmd-web')).toBeVisible()
  await page.getByTestId('tag-filter-internal').click()
  await expect(page.getByTestId('command-card-cmd-api')).toBeVisible()
  await expect(page.getByTestId('command-card-cmd-worker')).toBeVisible()
  await expect(page.getByTestId('command-card-cmd-web')).toHaveCount(0)
  await page.getByTestId('tag-filter-backend').click()
  await expect(page.getByTestId('command-card-cmd-api')).toBeVisible()
  await expect(page.getByTestId('command-card-cmd-worker')).toHaveCount(0)
  await page.getByTestId('tag-filter-all').click()
  await expect(page.getByTestId('command-card-cmd-web')).toBeVisible()
})

test('settings exposes the workspace environment table', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Open settings' }).click()
  await expect(page.getByRole('heading', { name: 'Settings' })).toBeVisible()
  await expect(page.getByTestId('environments-panel')).toBeVisible()
  await expect(page.getByTestId('environments-profile')).toHaveValue('local')
  await expect(page.getByLabel('API_URL local')).toHaveValue('http://127.0.0.1:8080')
  await page.getByTestId('environments-profile-toggle').click()
  await page.getByTestId('environments-profile-option-prod').click()
  await expect(page.getByTestId('environments-profile')).toHaveValue('prod')
  await expect(page.getByLabel('API_URL prod')).toHaveValue('https://api.example.com')
  await expect(page.getByLabel('API_URL local')).toHaveCount(0)
})

test('HTTP collection sidebars can collapse for editor focus', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('navigation', { name: 'Main navigation' }).getByRole('button', { name: 'HTTP', exact: true }).click()
  await expect(page.getByTestId('http-page')).toBeVisible()
  await expect(page.getByTestId('http-collection-http-hotel')).toBeVisible()
  await page.getByTestId('http-toggle-collections').click()
  await expect(page.getByTestId('http-collection-http-hotel')).toHaveCount(0)
  await expect(page.getByTestId('http-toggle-collections')).toHaveAttribute('aria-expanded', 'false')
  await page.getByTestId('http-toggle-requests').click()
  await expect(page.getByTestId('http-request-http-health')).toHaveCount(0)
  await page.getByTestId('http-toggle-collections').click()
  await expect(page.getByTestId('http-collection-http-hotel')).toBeVisible()
})

test('main sidebar can collapse, expand on hover, and pin open', async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 800 })
  await page.goto('/')
  const pin = page.getByTestId('sidebar-pin')
  await expect(pin).toHaveAttribute('aria-label', 'Collapse sidebar')
  await expect(page.getByTestId('app-shell')).toHaveClass(/sidebar-pinned/)
  await pin.click()
  await expect(pin).toHaveAttribute('aria-label', 'Pin sidebar open')
  await expect(page.getByTestId('app-shell')).toHaveClass(/sidebar-collapsed/)
  await expect(page.getByTestId('main-sidebar').locator('.brand-mark svg')).toBeVisible()
  await expect(page.getByTestId('main-sidebar').locator('.brand strong')).toBeHidden()
  await page.mouse.move(800, 200)
  await page.getByTestId('main-sidebar').hover()
  await expect(page.getByTestId('main-sidebar').locator('.brand strong')).toBeVisible()
  await pin.click()
  await expect(pin).toHaveAttribute('aria-label', 'Collapse sidebar')
  await expect(page.getByTestId('app-shell')).toHaveClass(/sidebar-pinned/)
  await page.mouse.move(800, 200)
  await expect(page.getByTestId('main-sidebar').locator('.brand strong')).toBeVisible()
})

test('HTTP collections send interpolated requests', async ({ page }) => {
  await page.goto('/')
  const nav = page.getByRole('navigation', { name: 'Main navigation' })
  const overview = nav.locator('.nav-group').filter({ hasText: 'Overview' })
  await expect(overview.locator('button span')).toHaveText(['Dashboard', 'HTTP', 'Active Runs', 'Ports', 'Logs', 'History'])
  await expect(nav.locator('.nav-group').filter({ hasText: 'Library' }).getByRole('button', { name: 'HTTP', exact: true })).toHaveCount(0)
  await nav.getByRole('button', { name: 'HTTP', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'HTTP collections' })).toBeVisible()
  await expect(page.getByTestId('http-page')).toBeVisible()
  await expect(page.getByTestId('http-collection-environment')).toHaveValue('local')
  await expect(page.getByTestId('http-collection-http-hotel')).toContainText('Hotel Meta API')
  await page.getByTestId('http-collection-name').fill('Hotel Meta')
  await page.getByTestId('http-collection-name').blur()
  await expect(page.getByTestId('http-collection-http-hotel')).toContainText('Hotel Meta')
  await expect(page.getByTestId('http-url-preview')).toContainText('http://127.0.0.1:8080/health')
  await expect(page.getByTestId('http-request-timeout')).toHaveValue('5000')
  await expect(page.getByTestId('http-request-name')).toHaveValue('Health')
  await expect(page.getByTestId('http-save-state')).toHaveText('Saved')
  await expect(page.getByTestId('http-save-body')).toBeDisabled()
  await expect(page.getByTestId('http-body-template')).toHaveValue('default')
  await page.getByTestId('http-add-body-template').click()
  await expect(page.getByTestId('http-body-template-name')).toHaveValue('Template 2')
  await expect(page.getByTestId('http-save-state')).toHaveText('Unsaved')
  await page.getByTestId('http-delete-body-template').click()
  await expect(page.getByTestId('http-save-state')).toHaveText('Saved')
  await page.getByTestId('http-add-body-template').click()
  await page.getByLabel('Request body').fill('{"city":"IST"}')
  await expect(page.getByTestId('http-save-state')).toHaveText('Unsaved')
  await page.getByTestId('http-beautify-body').click()
  await expect(page.getByLabel('Request body')).toHaveValue('{\n  "city": "IST"\n}')
  await page.getByTestId('http-save-body').click()
  await expect(page.getByTestId('http-save-state')).toHaveText('Saved')
  await page.getByTestId('http-body-template').selectOption({ label: 'Default' })
  await expect(page.getByTestId('http-save-state')).toHaveText('Saved')
  await expect(page.getByLabel('Request body')).toHaveValue('')
  await page.getByTestId('http-body-template').selectOption({ label: 'Template 2' })
  await expect(page.getByTestId('http-save-state')).toHaveText('Saved')
  await expect(page.getByLabel('Request body')).toHaveValue('{\n  "city": "IST"\n}')
  await page.getByTestId('send-http-request').click()
  await expect(page.getByTestId('http-response')).toContainText('"status": "ok"')
  await expect(page.getByTestId('http-response-beautify')).toBeVisible()
  await expect(page.getByTestId('http-response-beautify')).toBeDisabled()
  await expect(page.getByTestId('http-response-headers')).toContainText('Content-Type')
  await expect(page.getByTestId('http-response-curl')).toHaveAttribute('aria-expanded', 'false')
  await expect(page.getByTestId('http-response-curl')).not.toContainText('--max-time')
  await page.getByTestId('http-response-curl').click()
  await expect(page.getByTestId('http-response-curl')).toHaveAttribute('aria-expanded', 'true')
  await expect(page.getByTestId('http-response-curl')).toContainText('--max-time')
  const responseScreen = await page.getByTestId('http-response').locator('.http-response-screen').boundingBox()
  const copyBody = await page.getByTestId('http-response-copy-body').boundingBox()
  expect(responseScreen && copyBody).toBeTruthy()
  expect(copyBody!.x).toBeLessThan(responseScreen!.x + 180)
  await page.getByTestId('http-response-copy-body').click()
  await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toContain('"status": "ok"')
  await page.getByTestId('import-curl').click()
  await expect(page.getByTestId('curl-preview')).toContainText("curl -X GET '{{API_URL}}/health'")
  await page.getByTestId('http-request-url').fill('{{API_URL}}/ready')
  await expect(page.getByTestId('curl-preview')).toContainText("{{API_URL}}/ready")
  await page.getByTestId('curl-preview').fill("curl -X GET '{{API_URL}}/v1/status'")
  await expect(page.getByTestId('http-request-url')).toHaveValue('{{API_URL}}/v1/status')
  await page.getByTestId('http-save-body').click()
  await expect(page.getByTestId('http-save-state')).toHaveText('Saved')
  await page.getByTestId('curl-input').fill("curl -X GET 'http://127.0.0.1:8080/v1/hotels' -H 'Accept: application/json'")
  await page.getByTestId('import-curl-submit').click()
  await expect(page.getByTestId('http-request-url')).toHaveValue('{{API_URL}}/v1/hotels')
  await page.getByTestId('http-open-stack').click()
  await expect(page.getByTestId('stack-detail-drawer')).toContainText('Internal Microservices')
  await page.getByTestId('stack-tab-http').click()
  await expect(page.getByTestId('stack-http-panel')).toBeVisible()
  await expect(page.getByTestId('stack-http-request-http-health')).toContainText('Health')
  await page.getByTestId('stack-http-request-http-health').click()
  await expect(page.getByTestId('stack-http-response-curl')).toContainText("curl -X GET 'http://127.0.0.1:8080/")
  await expect(page.getByTestId('stack-http-response-curl')).toHaveAttribute('aria-expanded', 'false')
  await page.getByTestId('stack-send-http-http-health').click()
  await expect(page.getByTestId('stack-http-response')).toContainText('"status": "ok"')
  await expect(page.getByTestId('stack-http-response-beautify')).toBeVisible()
  await page.getByTestId('stack-http-response-copy-request').click()
  await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toMatch(/^curl -X GET 'http:\/\/127\.0\.0\.1:8080\//)
  await page.getByTestId('stack-http-response-curl').click()
  await expect(page.getByTestId('stack-http-response-curl')).toHaveAttribute('aria-expanded', 'true')
  const curl = (await page.getByTestId('stack-http-response-curl').innerText()).trim()
  expect(curl).toContain('--max-time')
  await page.getByTestId('stack-http-response-copy-response').click()
  await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toContain('Content-Type')
  await page.getByTestId('stack-http-response-copy-body').click()
  const body = await page.evaluate(() => navigator.clipboard.readText())
  expect(body).toContain('"status": "ok"')
  expect(body).not.toContain('Content-Type')
})

test('HTTP request delete asks for confirmation', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('navigation', { name: 'Main navigation' }).getByRole('button', { name: 'HTTP', exact: true }).click()
  await expect(page.getByTestId('http-page')).toBeVisible()
  await expect(page.getByTestId('http-request-name')).toHaveValue('Health')

  page.once('dialog', async dialog => {
    expect(dialog.type()).toBe('confirm')
    expect(dialog.message()).toContain('Health')
    await dialog.dismiss()
  })
  await page.getByTestId('delete-http-request').click()
  await expect(page.getByTestId('http-request-name')).toHaveValue('Health')

  page.once('dialog', async dialog => {
    expect(dialog.type()).toBe('confirm')
    await dialog.accept()
  })
  await page.getByTestId('delete-http-request').click()
  await expect(page.getByTestId('http-request-http-health')).toHaveCount(0)
  await expect(page.getByTestId('delete-http-request')).toHaveCount(0)
})

test('HTTP collection delete requires typing the collection name', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('navigation', { name: 'Main navigation' }).getByRole('button', { name: 'HTTP', exact: true }).click()
  await expect(page.getByTestId('http-page')).toBeVisible()
  await expect(page.getByTestId('http-collection-http-hotel')).toBeVisible()

  page.once('dialog', async dialog => {
    expect(dialog.type()).toBe('prompt')
    expect(dialog.message()).toContain('Hotel Meta API')
    await dialog.accept('wrong name')
  })
  await page.getByTestId('delete-http-collection').click()
  await expect(page.getByTestId('http-collection-http-hotel')).toBeVisible()

  page.once('dialog', async dialog => {
    expect(dialog.type()).toBe('prompt')
    await dialog.dismiss()
  })
  await page.getByTestId('delete-http-collection').click()
  await expect(page.getByTestId('http-collection-http-hotel')).toBeVisible()

  page.once('dialog', async dialog => {
    expect(dialog.type()).toBe('prompt')
    await dialog.accept('Hotel Meta API')
  })
  await page.getByTestId('delete-http-collection').click()
  await expect(page.getByTestId('http-collection-http-hotel')).toHaveCount(0)
})
