import { expect, test } from '@playwright/test'

test('dashboard navigation, details and launcher controls work', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Dashboard' })).toBeVisible()
  await expect(page.getByText('Demo data')).toBeVisible()
  await expect(page.getByText('No MCP clients')).toBeVisible()
  await expect(page.getByText('MCP Connected')).toHaveCount(0)
  await expect(page.getByTestId('run-card-run-api')).toBeVisible()
  const historyPanel = page.locator('section.panel').filter({ has: page.getByRole('heading', { name: 'Command History' }) })
  const portsPanel = page.locator('section.panel').filter({ has: page.getByRole('heading', { name: 'Port Overview' }) })
  const historyBox = await historyPanel.boundingBox()
  const portsBox = await portsPanel.boundingBox()
  expect(Math.abs((historyBox?.width ?? 0) - (portsBox?.width ?? 0))).toBeLessThan(2)
  expect(portsBox?.y ?? 0).toBeGreaterThan((historyBox?.y ?? 0) + (historyBox?.height ?? 0) - 1)

  await page.getByTestId('history-promote-hist-test').click()
  await expect(page.getByTestId('promote-modal')).toBeVisible()
  await expect(page.getByTestId('promote-modal')).toContainText('go test ./...')
  await page.getByTestId('promote-modal').getByRole('button', { name: 'New project' }).click()
  await page.getByLabel('New project name').fill('Dashboard project')
  await page.getByTestId('create-project-inline').click()
  await expect(page.getByLabel('Project')).toHaveValue(/project-/)
  await page.getByTestId('promote-modal').getByRole('button', { name: 'New collection' }).click()
  await page.getByLabel('New collection name').fill('Dashboard launchers')
  await page.getByTestId('create-collection-inline').click()
  await expect(page.getByLabel('Collection')).toHaveValue(/collection-/)
  await page.getByTestId('promote-modal').getByRole('button', { name: 'Cancel' }).click()

  await page.getByTestId('run-card-run-api').getByRole('button', { name: 'View logs for Backend API' }).click()
  await expect(page.getByTestId('detail-tab-logs')).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByTestId('log-panel')).toContainText('server listening')
  await page.getByTestId('run-detail-drawer').getByRole('button', { name: 'Close run details' }).click()

  await page.getByTestId('run-card-run-api').getByRole('button', { name: 'Inspect Backend API' }).click()
  await expect(page.getByTestId('run-detail-drawer')).toBeVisible()
  await page.getByTestId('detail-tab-logs').click()
  await expect(page.getByTestId('log-panel')).toContainText('server listening')
  await page.getByTestId('run-detail-drawer').getByRole('button', { name: 'Close run details' }).click()

  await page.getByRole('navigation', { name: 'Main navigation' }).getByRole('button', { name: 'Logs', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Live Logs' })).toBeVisible()
  await expect(page.getByTestId('logs-page').getByRole('tab', { name: 'Butcembu API', exact: true })).toBeVisible()
  await expect(page.getByTestId('logs-page').getByRole('tab', { name: /:8080/ })).toBeVisible()
  await expect(page.getByTestId('live-log-terminal')).toContainText('starting make go')
  await page.getByTestId('logs-page').getByRole('tab', { name: 'Butcembu Web', exact: true }).click()
  await expect(page.getByTestId('logs-page').getByRole('tab', { name: /:3000/ })).toBeVisible()
  await expect(page.getByTestId('live-log-terminal')).toContainText('starting npm run dev')

  await page.getByRole('button', { name: 'Services' }).click()
  await expect(page.getByRole('heading', { name: 'Saved Services' })).toBeVisible()
  await page.getByTestId('start-command-cmd-worker').click()
  await expect(page.getByTestId('stop-command-cmd-worker')).toBeVisible()
  await page.getByRole('button', { name: 'Add Notification Worker to favorites' }).click()
  await expect(page.getByRole('button', { name: 'Remove Notification Worker from favorites' })).toBeVisible()

  await page.getByRole('button', { name: 'Stacks' }).click()
  await expect(page.getByTestId('stack-card-stack-internal')).toBeVisible()
  await page.getByTestId('restart-stack-stack-internal').click()
  await expect(page.getByTestId('stop-stack-stack-internal')).toBeVisible()

  await page.getByRole('button', { name: 'Ports' }).click()
  await expect(page.getByRole('button', { name: 'Copy address for port 5432' })).toBeVisible()

  await page.getByRole('button', { name: 'Projects' }).click()
  await expect(page.getByTestId('projects-page')).toBeVisible()
  await page.getByTestId('project-project-api').click()
  await expect(page.getByRole('heading', { name: 'Butcembu API' })).toBeVisible()
  await expect(page.getByText('Pinned favorites')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Core services' })).toBeVisible()
  await expect(page.getByText('Added by Claude Code · discovered from Makefile').first()).toBeVisible()
  await page.getByTestId('add-collection').click()
  await page.getByRole('dialog', { name: 'New collection' }).getByLabel('Name').fill('Release ops')
  await page.getByTestId('confirm-collection').click()
  await expect(page.getByRole('heading', { name: 'Release ops' })).toBeVisible()

  await page.getByRole('button', { name: 'History' }).click()
  await page.getByTestId('history-promote-run-api').click()
  await expect(page.getByTestId('promote-modal')).toBeVisible()
  await page.getByLabel('Project').selectOption('project-web')
  await page.getByLabel('Collection').selectOption('collection-web-dev')
  await page.getByLabel('Tags').fill('release, web')
  await page.getByLabel('Pin to favorites').check()
  await expect(page.getByTestId('promote-modal').getByText('Ports are not selected automatically')).toBeVisible()
  await expect(page.getByTestId('promote-modal').getByRole('checkbox').first()).not.toBeChecked()
  await page.getByTestId('confirm-promote').click()
  await expect(page.getByTestId('promotion-receipt')).toContainText('Launcher saved')
  await page.getByTestId('promotion-receipt').getByRole('button', { name: 'View project' }).click()
  await expect(page.getByRole('heading', { name: 'Butcembu Web' })).toBeVisible()
  await expect(page.getByText('Saved from history').first()).toBeVisible()

  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Settings' })).toBeVisible()
  await expect(page.getByText('No MCP clients connected', { exact: true })).toBeVisible()
  await page.getByTestId('open-shutdown').click()
  await expect(page.getByRole('dialog', { name: 'Stop AgentShell?' })).toContainText('active runs')
  await expect(page.locator('.shutdown-impact').getByText('3', { exact: true })).toBeVisible()
  await page.getByTestId('confirm-shutdown').click()
  await expect(page.getByRole('heading', { name: 'Demo runtime stopped' })).toBeVisible()
})
